apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-ui
  template:
    metadata:
      labels:
        app: hello-ui
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - image: ialbakri/pipeline:0.0.11
        name: hello-ui
        ports:
        - containerPort: 443
